version: "3.8"
#Version of docker-compose specification
services:
  postgres:
    image: "postgres"
    restart: always
    volumes:
      - data:/data/db
    # environment:
    env_file:
      - ./env/db.env
  #backend:

  #frontend:
volumes:
  data:
