apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronend-deployment

##======The body of this deployment======
spec:
  replicas: 1

  #The pod label we want to match with this deployment
  selector:
    matchLabels:
      app: frontend

  # Here we define the pod that should be created as part of this deployment
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-node
          image: crawan/frontend:latest

---
#Service section
apiVersion: v1
kind: Service
metadata:
  name: fronend-service
spec:
  ## Selecter identify which other resources should be connected to this resources, here we define which pod should be controlled by this service
  selector:
    app: frontend ## Coming from pod label in deployment
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer
