name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cashe@v1
        with:
          path: ~/.npm
          #To generate a key if there are change in package-lock file or change on the runner
          key: ${{runner.os}}-mykey-${{hashFiles('**/package-lock.json')}}
          restore-key: |
            ${{runner.os}}-mykey-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
        working-directory: ./frontend
      - run: npm test -- --coverage
        env:
          CI: true
        working-directory: ./frontend
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
        working-directory: ./frontend
      # - name: Deploy to docker image
